
FROM fedora:latest

RUN dnf install -y 'dnf-command(config-manager)' && \
dnf install -y "https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-9.noarch.rpm"

# RUN sed -i 's/\(def in_container():\)/\1\n    return False/g' /usr/lib64/python*/*-packages/rhsm/config.py
RUN dnf update -y && dnf install bash gdb strace git yum-utils -y
# Install development tools and createrepo
RUN dnf -y update && \
    dnf -y install \
    gcc \
    gcc-c++ \
    make 

# Clean up Yum cache
RUN dnf clean all

# Create a non-root user and add sudo support
ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN dnf update -y && dnf install git sudo wget zsh -y
RUN groupadd -g 911 sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER vscode
