name: Build and Push Docker Images

# Schedule the workflow to run daily at 00:00 UTC
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rhel_version: [7, 8, 9]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./.devcontainer
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/ubi-nosub:rhel-${{ matrix.rhel_version }}
          build-args: |
            RHEL_VERSION=${{ matrix.rhel_version }}

      - name: Post build cleanup
        run: docker system prune -f
