name: Build and Push Fedora Images

# Schedule the workflow to run daily at 00:00 UTC
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read
  packages: write
  security-events: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./.devcontainer/Fedora
          file: ./.devcontainer/Fedora/Dockerfile
          push: true
          
          tags: ghcr.io/${{ github.repository_owner }}/devcontainer-rhelyeah:fedora-latest

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: 'ghcr.io/${{ github.repository_owner }}/devcontainer-rhelyeah:fedora-latest'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results-fedora.sarif'
          severity: 'CRITICAL,HIGH'
  
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results-fedora.sarif'

      - name: Post build cleanup
        run: docker system prune -f
