name: Build and Push RockyLinux Images

# Schedule the workflow to run daily at 00:00 UTC
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read
  packages: write
  security-events: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rhel_version: [8, 9]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        if: matrix.rhel_version == 9
        with:
          context: ./.devcontainer/RockyLinux
          file: ./.devcontainer/RockyLinux/Dockerfile
          push: true
          
          tags: ghcr.io/${{ github.repository_owner }}/devcontainer-rhelyeah:rocky-${{ matrix.rhel_version }}
          build-args: |
            RHEL_VERSION=${{ matrix.rhel_version }}
            CONFIG_PACKAGE=crb

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        if: matrix.rhel_version == 8
        with:
          context: ./.devcontainer/RockyLinux
          file: ./.devcontainer/RockyLinux/Dockerfile
          push: true
          
          tags: ghcr.io/${{ github.repository_owner }}/devcontainer-rhelyeah:rocky-${{ matrix.rhel_version }}
          build-args: |
            RHEL_VERSION=${{ matrix.rhel_version }}
            CONFIG_PACKAGE=powertools

